### ISSUE TITLE
Provide option for synchronous commits?

### ISSUE THREAD

**Issue by aiba** [jimpil/duratom#11]
Would it be possible to provide an option to have `reset!` and `swap!` commit the write to the backend synchronously before returning?  Sometimes it's important that the writer know that the change was successfully persisted.

**Comment by jimpil** [comment]
Hi there, thanks for the idea :+1: 

This commit (`541081331063f2cdbbfb847d832d680fae8d945f`) adds support for synchronous commits, but keeps async as the default. I may end up reworking how this is exposed over the coming days, but this is the core idea. 

You can expect a new release by end of week. Thanks again :)

**Comment by aiba** [comment]
Amazing, thank you! :-)

**Comment by jimpil** [comment]
Hey, just giving you the heads up, that I won't be able to cut a release this week, and I'm abroad on holidays for the entirety of May. The implementation is pretty much ready, so I'll have a look at this again early June at the first opportunity. Hope that's ok...

**Comment by jimpil** [comment]
I've just cut release `0.4.3`, which adds support for synchronous commits, per your suggestion. I was away on holidays for the entirety of May - that's why it took so long.

Basically all you need to do to turn this on is to provide a `:rw` map containing a `:commit-mode` key. The value can be any proper value (non-nil) that is also NOT `:duratom.core/async`. Hope that helps...

Thanks again for the suggestion :+1:
